project_id = "ffeimjfunghzxgeqiwma"

[functions.scrape-products]
verify_jwt = false

[functions.discover-products]
verify_jwt = false

[functions.discover-capterra]
verify_jwt = false

[functions.ai-generate-products]
verify_jwt = false

[functions.bulk-generate-reviews]
verify_jwt = false

[functions.brevo-api]
verify_jwt = false

[functions.bulk-generate-comparisons]
verify_jwt = false

[functions.discover-producthunt]
verify_jwt = false

[functions.publish-scheduled-posts]
verify_jwt = false

[functions.ai-playground]
verify_jwt = false

[functions.analyze-sentiment]
verify_jwt = false

[functions.bulk-selfhost-logos]
verify_jwt = false

[functions.bulk-fetch-photos]
verify_jwt = false
