/**
 * Scans public/{product,blog,guides}/ for .md files and emits
 * src/generated/md-manifest.ts — a string[] of site-relative paths.
 *
 * Consumed by <SeoHead> so the Markdown alternate <link> is only
 * emitted when the corresponding .md file actually exists on disk.
 * Without this gate we'd advertise broken alternates to AI crawlers
 * for any page that hasn't been generated yet.
 */
import { readdirSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";

const ROOTS = ["product", "blog", "guides"];
const PUBLIC = join(process.cwd(), "public");
const OUT = join(process.cwd(), "src/generated/md-manifest.ts");

const paths: string[] = [];
for (const root of ROOTS) {
  const dir = join(PUBLIC, root);
  if (!existsSync(dir)) continue;
  for (const f of readdirSync(dir)) {
    if (f.endsWith(".md")) paths.push(`/${root}/${f}`);
  }
}
paths.sort();

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/generate-md-manifest.ts — do not edit.
// Lists every Markdown alternate (.md) file present in /public.
export const MD_MANIFEST: ReadonlySet<string> = new Set(${JSON.stringify(paths, null, 2)});

export function hasMarkdownAlternate(path: string): boolean {
  if (!path) return false;
  const p = path.startsWith("http") ? new URL(path).pathname : path;
  return MD_MANIFEST.has(p.startsWith("/") ? p : \`/\${p}\`);
}
`,
);

console.log(`[md-manifest] wrote ${paths.length} entries → ${OUT}`);
