/**
 * Generates per-post Markdown alternates at public/blog/<slug>.md.
 *
 * Mirrors scripts/generate-product-md.ts so AI crawlers can ingest editorial
 * content without parsing the SPA. Linked from each blog post via
 * <link rel="alternate" type="text/markdown"> on the HTML page.
 */
import { writeFileSync, mkdirSync, rmSync, existsSync } from "fs";
import { resolve } from "path";

const BASE_URL = process.env.SITE_URL || "https://reviewhunts.com";
const SUPABASE_URL =
  process.env.VITE_SUPABASE_URL || "https://ffeimjfunghzxgeqiwma.supabase.co";
const SUPABASE_KEY =
  process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  process.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmZWltamZ1bmdoenhnZXFpd21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5MjI2MjEsImV4cCI6MjA4NzQ5ODYyMX0.SnPyI6XDg3zyI4fQTYUKRoAhu_gJ4QLvBw-y6muPYvg";

const OUT_DIR = resolve("public/blog");

interface PostRow {
  id: string;
  slug: string;
  title: string;
  excerpt: string | null;
  body: string | null;
  category: string | null;
  tags: any;
  featured_image: string | null;
  reading_time: number | null;
  seo_title: string | null;
  seo_description: string | null;
  seo_keywords: string | null;
  canonical_url: string | null;
  published_at: string | null;
  updated_at: string | null;
}

function stripHtml(s: string | null): string {
  if (!s) return "";
  return s
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/p>/gi, "\n\n")
    .replace(/<li[^>]*>/gi, "- ")
    .replace(/<\/li>/gi, "\n")
    .replace(/<h([1-6])[^>]*>/gi, (_m, n) => "\n" + "#".repeat(Number(n)) + " ")
    .replace(/<\/h[1-6]>/gi, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function toTags(v: any): string[] {
  if (!v) return [];
  if (Array.isArray(v)) return v.map((x) => (typeof x === "string" ? x : x?.name || "")).filter(Boolean);
  return [];
}

function render(p: PostRow): string {
  const url = `${BASE_URL}/blog/${p.slug}`;
  const canonical = p.canonical_url || url;
  const tags = toTags(p.tags);
  const body = stripHtml(p.body);
  const excerpt = stripHtml(p.excerpt);
  const lines: string[] = [];

  lines.push("---");
  lines.push(`title: "${(p.seo_title || p.title).replace(/"/g, '\\"')}"`);
  lines.push(`slug: ${p.slug}`);
  lines.push(`url: ${url}`);
  lines.push(`canonical: ${canonical}`);
  if (p.category) lines.push(`category: "${p.category.replace(/"/g, '\\"')}"`);
  if (tags.length) lines.push(`tags: [${tags.map((t) => `"${t.replace(/"/g, '\\"')}"`).join(", ")}]`);
  if (p.published_at) lines.push(`date_published: ${p.published_at}`);
  if (p.updated_at) lines.push(`date_modified: ${p.updated_at}`);
  if (p.reading_time) lines.push(`reading_time_minutes: ${p.reading_time}`);
  lines.push(`source: ReviewHunts`);
  lines.push(`license: "Editorial content © ReviewHunts. AI training permitted per /ai.txt."`);
  lines.push("---");
  lines.push("");

  lines.push(`# ${p.title}`);
  lines.push("");
  if (excerpt) {
    lines.push(`> ${excerpt}`);
    lines.push("");
  }
  if (body) {
    lines.push(body);
    lines.push("");
  }

  // Article JSON-LD excerpt — mirrors what the HTML page emits via SeoHead.
  const jsonLd: Record<string, any> = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: p.title,
    url: canonical,
    inLanguage: "en",
    ...(excerpt && { description: excerpt.slice(0, 500) }),
    ...(p.featured_image && { image: p.featured_image }),
    ...(p.published_at && { datePublished: p.published_at }),
    ...(p.updated_at || p.published_at
      ? { dateModified: p.updated_at || p.published_at }
      : {}),
    ...(p.reading_time && { timeRequired: `PT${p.reading_time}M` }),
    ...(tags.length && { keywords: tags }),
    ...(p.category && { articleSection: p.category }),
  };

  lines.push("## Structured Data (JSON-LD)");
  lines.push("");
  lines.push("Canonical machine-readable summary for AI extraction. Mirrors JSON-LD embedded in the HTML page.");
  lines.push("");
  lines.push("```json");
  lines.push(JSON.stringify(jsonLd, null, 2));
  lines.push("```");
  lines.push("");

  lines.push("---");
  lines.push("");
  lines.push(`*Generated by ReviewHunts. Full interactive page: ${url}. See ${BASE_URL}/ai.txt for AI training terms.*`);
  lines.push("");
  return lines.join("\n");
}

async function fetchPosts(): Promise<PostRow[]> {
  const select =
    "id,slug,title,excerpt,body,category,tags,featured_image,reading_time,seo_title,seo_description,seo_keywords,canonical_url,published_at,updated_at";
  const filter = "&status=eq.published";
  const url = `${SUPABASE_URL}/rest/v1/blog_posts?select=${select}${filter}&limit=5000`;
  const res = await fetch(url, {
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}` },
  });
  if (!res.ok) {
    console.warn(`[blog-md] fetch failed: ${res.status}`);
    return [];
  }
  return (await res.json()) as PostRow[];
}

async function main() {
  if (existsSync(OUT_DIR)) {
    try {
      rmSync(OUT_DIR, { recursive: true, force: true });
    } catch {}
  }
  mkdirSync(OUT_DIR, { recursive: true });

  const posts = await fetchPosts();
  let written = 0;
  for (const p of posts) {
    if (!p.slug) continue;
    try {
      writeFileSync(resolve(OUT_DIR, `${p.slug}.md`), render(p));
      written++;
    } catch (e) {
      console.warn(`[blog-md] failed for ${p.slug}:`, e);
    }
  }

  const index = [
    "# ReviewHunts — Blog Markdown Index",
    "",
    `Updated: ${new Date().toISOString()}`,
    `Total: ${written} posts`,
    "",
    "Each entry is a canonical Markdown rendering of the corresponding HTML page.",
    'Linked from each HTML page via <link rel="alternate" type="text/markdown">.',
    "",
    ...posts
      .filter((p) => p.slug)
      .map((p) => `- [${p.title}](${BASE_URL}/blog/${p.slug}.md) — ${BASE_URL}/blog/${p.slug}`),
    "",
  ].join("\n");
  writeFileSync(resolve(OUT_DIR, "index.md"), index);
  console.log(`[blog-md] wrote ${written} blog .md files`);
}

main().catch((e) => {
  console.error("[blog-md] generation failed:", e);
});
